florianholzapfel/express-restify-mongoose

README.md
lib/express-restify-mongoose.js
test/test.js

Sometimes it's beneficial to only pull down the primitive values in the response. Objects and arrays will be replaced with `true` to acknowledge their existence.

GET shallow model

---

README.md

When using Express4, it is good practice not to pass the whole app, but instead simply pass the router.

Updated readme to use Express4 Router

---

lib/permissions.js

Since most express apps use their own error handler the response should not be defined here, but rather in the user defined error handler.
I have not looked at the tests so I'm not sure whether or not this will break them.

usingExpress permissions error handling optimization

---

README.md
lib/express-restify-mongoose.js

This does two things:
1. Change the `onError` function signature from `res, next, err` to the conventional `err, req, res, next`
2. Support passing a custom handler as an option
```javascript
restify.defaults({
onError: function(err, req, res, next) {
res.status(err.status).json({
custom: 'data',
message: err.message
});
}
});
```

Improve onError and support custom handler

---

.gitignore
lib/express-restify-mongoose.js
lib/permissions.js
test/permissions.js

*This is an improvement on the thinking behind #92.*
The idea being that the permissions script shouldn't do it's own error handling, but rather pass it over to the existing `onError` function, default or custom. It also means permissions no longer need to know about `usingExpress`.
I changed the tests accordingly, but you might want to review them first to make sure they're really working as intended.

Remove permissions.js error handler, use existing handler instead

---

lib/express-restify-mongoose.js

At the moment, all the output responses flow through either the `onError` or `outputFn` callback, but in case of 204 (No content) responses (such as the response to a DELETE request), those were written directly to the Express (or Restify) response.
This patch makes the `outputFn` able to handle 204 responses. The default behaviour, though, has not changed.

Make 204 responses pass through the outputFn

---

lib/express-restify-mongoose.js

By cloning req.query, it can be accessed as expected after a request as
gone through the cleanQuery middleware.

refactor(clean): clone req.query to leave it intact

---

README.md
lib/express-restify-mongoose.js
test/test.js

When using "select('-myField') in mongoose, it excludes the
field named 'myField.
In restify, it used to include include a field named '-myField'
instead of excluding the field named 'myField'.

Add support for excluding fields in selection

---

lib/express-restify-mongoose.js

- refactor all calls to findOne & findOneAndX to use findById
if no alternative idProperty is provided
- extract duplicate creation of byId condition to a separate
method

use findById where possible

---

CHANGELOG.md
README.md
lib/express-restify-mongoose.js
package.json
test/resource_filter.js
test/test.js

- Introduces many breaking changes, lib needs updates

chore(deps): bump mongoose to ~4.0.0

---

CHANGELOG.md
lib/express-restify-mongoose.js
lib/permissions.js
test/express.js
test/permissions.js
test/restify.js

Basically, what used to be strict mode is now always on.
- Allow DELETE without id
- Allow POST with id
- Disallow PUT without id
Ugh, that was intended to be two PR's. Oh well.
The second commit is about passing req into outputFn

refactor(options): remove strict

---

lib/express-restify-mongoose.js

A custom postCreate or postDelete may set it's own status code.
Currently when you do something like this:
```javascript
postCreate: function(res, result, done) {
var err = new Error("Something went wrong!");
err.status = 500;
done(err);
}
```
Instead of sending 500, it gets overwritten with 400. This PR checks if status was already set and otherwise sets 400.

fix: do not override status if already set

---

README.md
lib/express-restify-mongoose.js
package.json
test/test.js

I added a limit option. This is useful to prevent huge result sets being returned and to enforce pagination (with skip and limit query parameters).
Exampel: `{ limit: 10 }` in the options object will limit all queries (except count queries) to 10. If a limit query parameter is supplied, it can only override this limit with a smaller number.
Tests are included. What do you think? :)

Add limit option

---

lib/express-restify-mongoose.js

Simple change to allow passing an array of fields to `options.private` and `options.protected` rather than a comma-separated list of fields.

feat: allow array of private/protected fields

---

lib/express-restify-mongoose.js

It will only work with Express 4 and allows this:
```javascript
restify.serve(router, TransactionModel, {
...
}).get('/:id/refund', function(req, res, next) {
// /api/v1/transactions/:id/refund
res.status(200).send(req.params.id);
});
```
Improvements welcome, I'm not sure how or if this could be achieved with Express 3 or restify.
Either way, tests must be added before merging.

feat: custom method chaining

---

package.json

Since mongoose has switched to semver since version 4, this is now safe.

chore(deps): depend on latest mongoose minor

---

lib/express-restify-mongoose.js

Fixes so that unspecified properties aren't ignored when saving to db.
http://mongoosejs.com/docs/guide.html#strict

Allow unspecified properties to be saved when schema's strict option is set to false.

---

lib/express-restify-mongoose.js

To support field validation on atomic updates without performing a non-atomic find and save.

Add the runValidators option to findOneAndUpdate call.

---

lib/express-restify-mongoose.js
test/integration/middleware.js

This adds: preCreate, preRead, preUpdate and preDelete middleware.
- `preMiddleware` > `preCreate/Read/Update` -> `access`
- `preMiddleware` > `preDelete`
This also paves the way for implementing #148

feat: preCreate/Read/Update/Delete middleware

---

lib/operations.js
test/integration/create.js
test/integration/update.js

The `else` couldn't catch everything, check for undefined instead.
This should be backported to 1.x also.
Closes #172

fix: make sure to always set value when updating

---

lib/resource_filter.js
test/integration/read.js
test/integration/setup.js

`currSchema` is undefined when trying to do a deep populate (unsupported by mongoose)
`path` is undefined if the field doesn't exist
In both cases, it is safe to ignore the filtering since there is no data.
Closes #174 and #160

fix(filter): check if schema and path are defined

---

lib/express-restify-mongoose.js
lib/middleware/filterAndFindById.js
lib/operations.js
test/integration/middleware.js

This would give access to the document in `preUpdate` and `preDelete` middlewares when `findOneAnd* = false`
```javascript
findOneAndUpdate: false,
preUpdate: function (req, res, next) {
if (req.erm.document.isAwesome) {
return next()
}
res.sendStatus(403)
}
```
It also opens the door for doing clever things with delete:
```javascript
findOneAndRemove: false,
preDelete: function (req, res, next) {
if (!req.erm.document) {
return res.sendStatus(403) // probably don't want to delete everything
}
req.erm.document.set('deletedAt', new Date())
req.erm.document.save(function (err) {
res.sendStatus(204)
})
}
```
Closes #148

feat: provide doc to preUpdate/Delete when findOneAnd* is false

---

lib/express-restify-mongoose.js
test/integration/options.js

Using `.defaults()` without an explicitly provided preUpdate
resulted in accidental duplication of findOneAndUpdate
when multiple models were attached.
Resolves [#182](https://github.com/florianholzapfel/express-restify-mongoose/issues/182)

fix: prevent defaults() from duplicating preUpdates/Deletes

---

lib/express-restify-mongoose.js

Added deprecation warnings to POST/PUT update methods.
@KATT @florianholzapfel Can you review the wording? I spent entirely too much time trying to write a succinct message!

deprecate: POST/PUT update methods

---

lib/middleware/prepareQuery.js
test/integration/delete.js
test/integration/read.js

MongoDB 3.2 requires skip and limit to be numbers, so we must parse it internally.
Closes #215

fix(query): run parseInt on skip and limit parameters

---

lib/resource_filter.js
package.json

`_.pluck` needs to be replaced by `_.map`
[Reference](http://colintoh.com/blog/lodash-10-javascript-utility-functions-stop-rewriting#two_of_the_same_kind)

chore(deps): update lodash (4.0.0)

---

src/express-restify-mongoose.js
src/operations.js
src/resource_filter.js
test/integration/access.js

This will filter out distinct queries containing a private or protected field. ~~The reason for filtering post-query is to mimic behavior where the field did not exist, which is to return an empty array.~~ As suggested, distinct fields are now verified before querying, thus saving a database call and fields that are filtered out return an empty array, as if the field did not exist.
We should be able to backport this very easily to 2.x, however previous versions would require significantly more effort.
@smirea Can you test the patch on your end?
Closes #252

fix(distinct): filter private/protected keys

---

.travis.yml

So I just realized we have been building every commit twice.
This will make TravisCI build PRs, subsequent pushes and merges only once.
Credit: http://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-build-pull-requests-merges-to-master-w-o-redunda

fix(ci): prevent testing everything twice

---

.travis.yml
package.json

Latest alpha of istanbul fixes this issue by adding support for source maps. Pre-release builds are not ideal, but since this is non-critical and only runs on CI, there is no risk involved.
Tests run on compiled files, but coverage is reported on source files.
Closes #262

Update istanbul to fix missing coverage data

---

package.json
src/middleware/prepareQuery.js
test/integration/read.js
test/integration/setup.js

This tries to *guess* if a value being `JSON.parse`'d is likely to be a coordinate. The key must be `coordinates` and the value must be an array of two numbers.
However, I'm not sure if it may cause issues in some cases.
Closes #187

fix(query): leave coordinates array as-is in geo queries

---

v2/index.md

The documentation says, that `{"key": 0}` is a valid sort object. But its leading to a MongoError "bad sort specification", because the mongodb does only allow `1` or `-1` when specifying the sort order like this: https://docs.mongodb.org/manual/reference/method/cursor.sort/#ascending-descending-sort

Update sort documentation

---

src/express-restify-mongoose.js
src/middleware/prepareQuery.js
test/integration/options.js
test/integration/read.js
test/unit/middleware/prepareQuery.js

This add an `allowRegex` option that defaults to `true` for backward compatibility. When set to `false`, queries attempting to use a regex (either with `~` or `$regex`) will send back an error.
Closes #195

feat(options): add allowRegex

---

package.json

See [npm issue #3059](https://github.com/npm/npm/issues/3059) for details.

fix(ci): prevent prepublish from running after install

---

src/middleware/prepareOutput.js
test/unit/middleware/prepareOutput.js

- Useful in v1.x and earlier
- Removed from documentation since v2.0 in favor of `req.erm.result` and
`req.erm.statusCode`

refactor(ouput): remove undocumented parameter

---

CHANGELOG.md

Breaking changes to be introduced in 4.0
* improved default error middleware by serializing error objects and removing stack traces
* fixed Mongoose async middleware error propagation
* fixed requests to always set `req.erm.statusCode`
* removed `statusCode` from error object and response body
* removed undocumented `outputFn` parameter, use `req.erm.result` and `req.erm.statusCode`

chore(docs): update changelog for 4.0

---

.travis.yml
package.json
test/integration/create.js
test/integration/options.js
test/integration/read.js
test/integration/update.js

Closes #319
Breaking changes:
- Drop support for Node 0.10 & 0.12
- Update to restify 4, see their [changelog](https://github.com/restify/node-restify/blob/5.x/CHANGES.md#400) for details

Drop Node 0.10 & 0.12, add Node 7, update restify

---

package.json

make sure we are not vulnerable to https://nodesecurity.io/advisories/method-override_regular-expression-denial-of-service

chore(deps): update method-override

---

index.d.ts

closes  #191, adding the type definition file to the library itself instead of the DefinitelyTyped repo.

TypeScript type definition file

---

src/express-restify-mongoose.js
src/operations.js

Some use-cases desire PUT to also create a resources, e.g., when the ID is client-controlled. In such cases, the PUT operation should create a resource if it does not exists. This is called `upsert` in MongoDB. This PR adds an options for that.

Allow upsert on PUT

---

index.d.ts
package.json

Fixes #400: This PR adds the TypeScript definition file to `package.json` and fixes a TS7010 error in the TypeScript definition file.

Fix TypeScript configuration

---

src/middleware/prepareOutput.js

Because of the condition `if (options.totalCountHeader && req.erm.totalCount)`, a total count of will never be put in the header if no data is returned since 0 is evaluated as false.
This can be problematic with some client implementations which use this header to know if data is present or not.

Show totalCount even when it's 0.

---

src/express-restify-mongoose.js

Simple enhancement: When the function getModel() is called, the request is passed as call arg. 
@Zertz : I haven't seen any tests for the model factory right now. If any, I would place them in the /test/integrations/options.js file. If there is any interest, I would submit them in a different PR. Your opinion?
BTW: modelFactory is not yet registered in index.d.ts. Is there a special reason?

passing request object to getModel in modelFactory

---

test/integration/setup.js

If the environment supplies a MONGO_URL, it takes precedence before the localhost address, so that mongos with authentication or other specific settings configurable by url can be used without switching the database environment.

MONGO_URL as alternative to constant value 

---

package.json
src/middleware/prepareQuery.js
test/integration/setup.js
test/integration/update.js
test/unit/middleware/prepareQuery.js

This updates the peer dependency of mongoose to v6.2.1 and fixes the following migration issues:
- Maintains the previous behaviour where unrecognized paths was set to be populated, i.e. the population is simply ignored. The [new behavior in Mongoose 6](https://mongoosejs.com/docs/migrating_to_6.html#strictpopulate) is to return an error unless `strictPopulate: false` is used as an option. prepareQuery.js is updated to add this option.
- Tests are updated to [reflect the change](https://mongoosejs.com/docs/migrating_to_6.html#mongoerror-is-now-mongoservererror) from `MongoError` to `MongoServerError`
- [Deprecated Mongoose options](https://mongoosejs.com/docs/migrating_to_6.html#no-more-deprecation-warning-options) are removed from the tests.
Fixes issue #432
_**Note:** I encountered some …

Mongoose 6

---

package.json
src/express-restify-mongoose.ts

I don't know where it got lost, but I think back when ERM 8 got released, we lost the changes introduced by #420.
This PR adds them back (allowing for multi tenancy again #393) and also optionally allows getModel to be async (or return a Promise), so that apps using it don't have to operate synchronously.

Fix support for modelFactory

---

package.json
src/express-restify-mongoose.ts
src/middleware/filterAndFindById.ts
src/operations.ts

I found another bug regarding the modelFactory. Many places in the code were exclusively using the initially provided model instead of the model dynamically provided through modelfactory.getModel.
As we don't have any integration tests for this feature, I created a little test script to verify that it works as expected:
``` JavaScript
var express = require('express')
var bodyParser = require('body-parser')
var methodOverride = require('method-override')
var mongoose = require('mongoose')
var restify = require('express-restify-mongoose')
const request = require('request-promise')
var app = express()
var router = express.Router()
app.use(bodyParser.json())
app.use(methodOverride())
mongoose.connect('mongodb://localhost/database')
var customerSchema = new mongoose.Schema({
name: { type: …
```

Fix a modelFactory bug

---

src/express-restify-mongoose.ts
src/operations.ts
src/types.ts

This change will add the option "updateDeep," which gives the user more control to choose whether they want to use "moredots()" during the update process or not.

Added option updateDeep

---

src/getQuerySchema.ts

The populate option in the populate query was enabled by default in previous version the project.
But recent version is not containing the nested populate option in the PopulateOptionsSchema. 
Because of this absence, the query with nested populate option like below is not working properly.
`populate=[{"path":"course", "populate":{"path":"badge"}}]`
By adding the property for the nested populate definition, the query with nested popluate working well.

Enable nested populate query again.
