florianholzapfel/express-restify-mongoose

- lib/express-restify-mongoose.js
HTTP Status Code: http://www.restapitutorial.com/httpstatuscodes.html
POST -> 201 - Created
PUT -> 200 - OK
DELETE -> 204 - No Content
GET -> 200 - OK
> validate HTTP Status Code

- README.md
Add **bold** highlighting to property names in arguments section, making the list easier to scan. Also cleaned up inline md code blocks.
> Highlight property names in Arguments.

- .travis.yml
See: http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
This should allow for faster builds
> chore(ci): use Travis container infrastructure

- lib/express-restify-mongoose.js
- test/test.js
> Use status code 200 for GETting empty lists

- lib/express-restify-mongoose.js
This adds a description for Content-Type errors and splits missing and invalid values.
> improve: send an error description with 400's

- CHANGELOG.md
- lib/express-restify-mongoose.js
- package.json
- test/test.js
There are postCreate and postDelete hooks, but nothing for updates. There it is, with tests and all.
> Feature: postUpdate

- lib/resource_filter.js
- package.json
- test/integration/access.js
- test/integration/read.js
- test/integration/resource_filter.js
- test/integration/setup.js
It looks like it works, but it's ugly, hard to understand and it needs more tests.
**Edit 1**: This is broken, the filter makes more assumptions than I realized.
**Edit 2**: Possibly less broken, more tests needed with crazy schema design.
> fix: filter nested, populated fields

- lib/express-restify-mongoose.js
- lib/middleware/prepareOutput.js
- lib/resource_filter.js
- package.json
- test/integration/access.js
- test/integration/middleware.js
- test/integration/resource_filter.js
- test/integration/setup.js
Added tests for filtering:
- Arrays of populated documents
- Nested populated documents
- Populated document in a discriminator
Improved:
- Use lodash rather than custom functions whenever possible
- Handle null middleware
> handle filtering of nested, populated and discriminator fields

- lib/middleware/filterAndFindById.js
- lib/operations.js
- test/integration/virtuals.js
I wasn't able to run tests, but hopefully this works! :)
(I tried running `npm install` but when I tried to run the test, it complained "Cannot find module 'generate-object-property' ")
> add option to set readPreference on request

- package.json
This should not break anything...
> chore(deps): update inflection

- lib/express-restify-mongoose.js
- test/integration/delete.js
> fix: Adding prepareQuery middleware into DELETE

- lib/express-restify-mongoose.js
This PR adds the model to the req.erm object so that the requested model is available for subsequent queries.
Discussed in Issue #211
> feat: Adding model to req.erm

- lib/middleware/prepareOutput.js
- lib/operations.js
- test/integration/options.js
> feat: option to include total count header

- lib/express-restify-mongoose.js
Backport of PR #216 for the v1.x branch
> fix(query): run parseInt on skip and limit parameters

- CHANGELOG.md
> Update CHANGELOG for v3

- lib/express-restify-mongoose.js
- lib/operations.js
- lib/resource_filter.js
- test/integration/access.js
> fix(distinct): filter private/protected keys (2.x)

- index.md
Replace endpoint names in the documentation by the singular version.
> Customers -> Customer

- test/integration/read.js
> chore(test): confirm invalid json doesn't throw

- test/integration/access.js
- test/integration/contextFilter.js
- test/integration/middleware.js
- test/integration/options.js
- test/integration/update.js
More tests, less code!
Every update related test now runs on PATCH, POST and PUT. Iterating on those methods also removed a bunch duplicate code.
> chore(test): iterate through all update methods

- package.json
- src/buildQuery.js
- src/operations.js
- test/integration/read.js
- test/unit/buildQuery.js
> fix(query): return a promise to catch exceptions

- src/operations.js
- test/integration/options.js
> Fix queries combining distinct & total count header

- package.json
> chore(deps): update lodash

- package.json
> chore(deps): update mocha

- .travis.yml
> chore(ci): remove node 5 & 7

- src/operations.js
- test/integration/update.js
Closes #294 (Rebase from #317)
> Fix issue #294 (Rebase from #317)

- CHANGELOG.md
- src/middleware/prepareOutput.js
- test/integration/middleware.js
- test/unit/middleware/prepareOutput.js
> Call postProcess async when outputFn returns a Promise

- package.json
It looks like eslint issue 10599 https://github.com/eslint/eslint/issues/10599
> Fix CI error due to ESLint error trying to lint node_modules

- .github/workflows/node.js.yml
- .github/workflows/npm-publish.yml
- README.md
- package-lock.json
- package.json
- src/middleware/prepareOutput.js
- test/integration/create.js
- test/integration/options.js
- test/integration/update.js
This isn't perfect but should be good enough to bring the library in a state where the next version can be released safely.
> Maintenance updates

- v4/index.md
> Clarify lean docs
